#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>

#define H_NAME "image.h"
#define HEADER "/*\n * File generated by hgen\n * (c) antonio@naiki.com\n"
#define VERSION "v1.0"
#define MAX_COL 15

void usage(char *argv0) {
  fprintf(stderr, "Usage:\n");
  fprintf(stderr, "\t%s binary_image\n", argv0);
}

int main(int argc, char *argv[]) {
  FILE *fp, *out;
  unsigned char c, buff[1024], first_byte;
  int retval, col, done, debug;
  unsigned long image_size, count;
  struct stat st;
  time_t t;

  printf("%s %s - .h Generator.\n", argv[0], VERSION);
  printf("Comments to antonio@naiki.com\n\n");

  /* arg processing */
  if (argc != 2) {
    fprintf(stderr, "%s: Error, Wrong args.\n", argv[0]);
    usage(argv[0]);
    exit(1);
  }

  fp = fopen(argv[1], "rb");
  if (!fp) {
    fprintf(stderr, "%s: Error opening %s\n", argv[0], argv[1]);
    return 1;
  }

  out = fopen(H_NAME, "wt+");
  if (!fp) {
    fprintf(stderr, "%s: Error creating %s\n", argv[0], H_NAME);
    return 1;
  }

  debug = 0;

  strcpy(buff, HEADER);
  fprintf(out, "%s", HEADER);
  fprintf(out, " * %s\n *\n", VERSION);
  fflush(out);

  stat(argv[1], &st);
  image_size = (unsigned long)st.st_size;
  printf("%s: Image size - %lu bytes.\n\n", argv[0], image_size);
  t = time(NULL);
  strcpy(buff, ctime(&t));
  buff[strlen(buff) - 1] = 0;
  fprintf(out, " * Date: %s\n", buff);
  fprintf(out, " * Original File: %s\n", argv[1]);
  fprintf(out, " * File Size: %lu\n", st.st_size);
  fprintf(out, " */\n\n");
  fflush(out);

  fprintf(out, "#ifndef __IMAGE_H__\n\n");

  fprintf(out, "static unsigned long image_size = %lu;\n", image_size);
  fprintf(out, "\nstatic unsigned char image_data[] = { \n");
  fflush(out);

  col = 0;
  done = 0;
  count = 0;
  first_byte = 1;
  while (!done) {
    retval = fread(&c, sizeof(char), 1, fp);
    count++;
    if (feof(fp)) {
      fprintf(out, " };\n\n");
      fflush(out);
      done++;
    } else {
      if (!first_byte) {
        fprintf(out, ",");
      } else {
        first_byte = 0;
      }
      if (col <= MAX_COL) {
        col++;
        /* fprintf(out,"%3u",c); let's save some space */
        fprintf(out, "%u", c);
      } else {
        col = 0;
        /* fprintf(out,"\n%3u",c); let's save some space */
        fprintf(out, "\n%u", c);
      }
      if (debug)
        printf("Bytes opened so far: %lu\r", count);
    }
  }

  fprintf(out, "#define __IMAGE_H__\n\n#endif\n");

  return 0;
}
